OOP school library: refactor your code ♻️
ismailmunyentwari9/OOP-school-library pull request #5
Opened 2023-05-22 14:23 UTC by ismailmunyentwari9

# What We have done in this Part of project 🥇 

- [ ] Use YAGNI, KISS, and DRY rules and Ruby style guide.
- [ ] Follow SOLID principles.
# 🧠  Skills Obtained in this project 🌳 

- [ ] Describe the `SOLID principles` of `OOP`.
- [ ] `Refactor your own Ruby code` after gaining new knowledge.
- [ ] Apply `Ruby best practices` and `language style guides` in code.

2023-05-22 16:09 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @ismailmunyentwari9 @Caren-Koroeny, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of Git flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Great UI design. 💻 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-22 16:09 UTC, anagudelogu commented on main.rb
>    end
- [ ] Instead of passing these parameters (people, books, rentals) and passing them all over each one of your methods, I think is better to move them to your `App` class since it should be the one keeping the global state of your App. 🤓 🔧 

```rb
class App
  def initialize
    @books = []
    @people = []
    @rentals = []
  end
end

# Remember to refactor all your methods inside your app.rb file to interact
# with these new variables instead of the parameters.
```

- [ ] Also, to avoid passing the `app` parameter all over your methods, you can simply initialize `@app = App.new` at the initialize method of your main class. This way you have it available to use in all methods using the `@app` instance variable and not as a parameter. Remember to keep the code DRY! 🤓 🔧 

```rb
class Main
  def initialize
    @app = App.new
  end

# Remember to refactor all your methods inside your app.rb file to interact
# with this new variable instead of the one passed as parameter.
end
```

2023-05-22 16:09 UTC, anagudelogu commented on main.rb
> +  end
- [ ] Also, If you notice, most of these methods are just wrappers over the ones you have in your `app.rb` file. When you apply the changes I suggested, you shouldn't need any of these, just the ones in your app, ending up with less code and simpler logic KISS! 🤓 🔧

2023-05-23 06:56 UTC, amejid approved these changes
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Linter check passing :heavy_check_mark: 
- Correct workflow :heavy_check_mark: 
- DRY principle followed when refactoring :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-23 07:52 UTC, merged